### ISSUE TITLE
请求json文件跨域

### ISSUE THREAD

**Issue by limitop** [kagurazakayashi/NyarukoPlayer.js#1]
$(document).ready(function(){
    nyarukoplayer_init("indexfiles/nyaruko.json",true);
});
![image](https://user-images.githubusercontent.com/44015683/53690862-a053e500-3dad-11e9-8104-844bc6e69a80.png)

**Comment by kagurazakayashi** [comment]
尝试在本地服务器上运行吧，直接本地文件方式打开确实有这个。
不要直接通过双击打开网页。
可以装个 nginx 或者 iis 等，尝试用类似 `http://localhost/...` 这样的方式访问。

**Comment by kagurazakayashi** [comment]
你可以下载一个完整的演示程序（不保证连接永久有效）: 
[提取码：efhs](https://pan.baidu.com/s/1AW3lOpqCVmFc6r2wrDPTbg)

**Comment by limitop** [comment]
> 你可以下载一个完整的演示程序（不保证连接永久有效）:
> [提取码：efhs](https://pan.baidu.com/s/1AW3lOpqCVmFc6r2wrDPTbg)

多谢
